---
# Elasticsearch Ansible Variables
elasticsearch_user: elasticsearch
elasticsearch_group: elasticsearch
elasticsearch_download_url: https://artifacts.elastic.co/downloads/elasticsearch
elasticsearch_version: 5.4.1
elasticsearch_apt_repos:
  - 'ppa:webupd8team/java'
elasticsearch_apt_java_package: oracle-java8-installer
elasticsearch_java_home: /usr/lib/jvm/java-8-oracle
elasticsearch_apt_dependencies:
  - htop
  - ntp
  - unzip
  - atop
elasticsearch_max_open_files: 65536
elasticsearch_max_threads: 2048
elasticsearch_home_dir: /usr/share/elasticsearch
elasticsearch_plugin_dir: /usr/share/elasticsearch/plugins
elasticsearch_log_dir: /var/log/elasticsearch
elasticsearch_data_dir: /mnt
elasticsearch_work_dir: /tmp/elasticsearch
elasticsearch_conf_dir: /etc/elasticsearch
elasticsearch_pid_dir: /var/run/elasticsearch
elasticsearch_service_startonboot: yes
elasticsearch_timezone: "Etc/UTC"  # Default to UTC
elasticsearch_max_locked_memory: "unlimited"

elasticsearch_service_state: started

# Non-Elasticsearch Defaults
apt_cache_valid_time: 300 # seconds between "apt-get update" calls.
elasticsearch_install_java: "true"
