---
- hosts: master
  any_errors_fatal: true

  vars_files:
    - ../vars/ursa.yml

  tasks:

    - name: Ensure {{ blacklist_downloads_directory }} directory=exists
      file: path={{ blacklist_downloads_directory }} state=directory

    - name: Get today's date
      shell: date +%Y-%m-%d
      register: dateOutput

    - name: Set variables | todays_download_directory
      set_fact: todays_download_directory={{ blacklist_downloads_directory}}/{{ dateOutput.stdout }}

    - name: Ensure daily download directory=exists
      file: path={{ todays_download_directory }} state=directory

    - name: Set variables | blacklist_download_path
      set_fact: blacklist_download_path={{ todays_download_directory }}/malware-domains-{{ dateOutput.stdout }}.zip

    - name: Check if today's compressed zone file, {{ blacklist_download_path }} exists
      stat: path={{ blacklist_download_path }}
      register: blacklist_download_path_exists

    - name: Today's malware-domains Blcklist Not Found | Download today's malware-domains file
      shell: wget -O {{ blacklist_download_path }} http://malware-domains.com/files/domains.zip
      when: blacklist_download_path_exists.stat.exists == False
      tags:
        - download