---
- name: Ensure {{ project_directory }} directory exists
  file: path={{ project_directory }} state=directory

- name: Ensure {{ data_directory }} directory exists
  file: path={{ data_directory }} state=directory

- name: Ensure {{ config_directory }} directory exists
  file: path={{ config_directory }} state=directory

- name: Ensure {{ logs_directory }} directory exists
  file: path={{ logs_directory }} state=directory

- name: Ensure {{ history_directory }} directory exists
  file: path={{ history_directory }} state=directory

- name: Ensure {{ zone_downloads_directory }} directory exists
  file: path={{ zone_downloads_directory }} state=directory

- name: Ensure {{ zone_unzips_directory }} directory exists
  file: path={{ zone_unzips_directory }} state=directory

- name: Ensure {{ zone_sorts_directory }} directory exists
  file: path={{ zone_sorts_directory }} state=directory

- name: Ensure {{ comm_delta_directory }} directory exists
  file: path={{ comm_delta_directory }} state=directory

- name: Ensure {{ formatted_delta_directory }} directory exists
  file: path={{ formatted_delta_directory }} state=directory

- name: Ensure {{ persisted_zone_downloads_directory }} directory exists
  file: path={{ persisted_zone_downloads_directory }} state=directory

- name: Ensure {{ persisted_comm_delta_directory }} directory exists
  file: path={{ persisted_comm_delta_directory }} state=directory

- name: Ensure {{ persisted_formatted_delta_directory }} directory exists
  file: path={{ persisted_formatted_delta_directory }} state=directory
