---
- name: Install Python utils
  apt:
    pkg: {{ item.package }}
    update_cache: yes
    state: latest
  with_items: "{{logstash_python_utils}}"

- name: Install dependencies
  apt:
    pkg: {{ item }}
    state: present
  with_items: "{{logstash_apt_dependencies}}"

- name: java | Accept Oracle license prior JDK installation
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    creates=/usr/lib/jvm/java-8-oracle

- name: java | Update repositories
  apt_repository:
    repo: {{ item }}
    state: present
    update_cache: yes
  with_items: "{{java_apt_repos}}"

- name: java | Install dependencies
  apt:
    pkg: {{apt_java_package}}
    state: present

- name: Install haveged for increase in entropy
  apt:
    pkg: haveged
    state: present
