---
- hosts: rabbit_mq_cluster
  become: yes
    
  tasks:
    # - name: rabbitmq_clustering | UNMARKING clustered
    #   file:
    #     path: /etc/rabbitmq/clustered
    #     state: absent

    - name: rabbitmq_clustering | restarting rabbitmq-server on master
      service:
        name: rabbitmq-server
        state: restarted