---
- hosts: rabbit_mq_cluster
  become: true

  tasks:
    - name: updating /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ item }} {{ hostvars[item].name }}"
        line: "{{ item }} {{ hostvars[item].name }}"
        state: present
      with_items: "{{ groups['rabbit_mq_cluster'] }}"
      
- hosts: rabbit_mq_cluster
  become: true
  vars:
    max_open_files: 65536
    config_rabbitmq_ha: false
    enable_rabbitmq_clustering: false
    rabbitmq_master: "{{ hostvars[groups['rabbit_mq_cluster'][0]]['name'] }}"
    # - pri_domain_name: 'test.vagrant.local'
  roles:
    - role: rabbitmq

  tasks:
