---
  - name: Stop pdns-recursor before update
    service:
      name: pdns-recursor
      state: stopped
    ignore_errors: yes

  - name: Copy pdns-recursor configuration (recursor.conf)
    template: src=recursor.conf.j2
              dest="{{ pdns_config_dir }}"/recursor.conf
              owner=root
              group=root
              mode=0644

  - name: Restart pdns-recursor before upgrading
    service:
      name: pdns-recursor
      state: restarted
