---
- hosts: es_cluster
  become: yes
  serial: 1
  tasks:
    - name: Stop ES
      service:
        name: elasticsearch
        state: stopped

    - name: Stop all processes started by ES
      command: pkill -u elasticsearch
      become: yes
      ignore_errors: yes

    - name: Reboot Machine
      shell: reboot
      async: 0
      poll: 0

    - name: Wait for reboot to complete
      local_action:
        module: wait_for
          host="{{ ansible_host }}"
          delay=30
          timeout=60
          state=started

    - name: Make sure ES is running
      command: service elasticsearch status
      become: yes
      register: status

    - name: Stop all processes started by ES
      command: pkill -u elasticsearch
      become: yes
      when: status|failed

    - name: Start ES
      service:
        name: elasticsearch
        state: started
      when: status|failed
