---
- hosts: es_cluster
  become: yes
  serial: 1
  pre_tasks:
    - name: Set variable | es_master_ip
      set_fact: es_master_ip="192.168.0.204" # "{{ hostvars[groups['es_master'][0]]['ansible_eth0']['ipv4']['address'] }}"

    - name: Disable routing allocation
      command: bash rolling_upgrade_scripts/disable_routing_allocation.sh
      register: DRA
      until: DRA|success
      delegate_to: 127.0.0.1
      delay: 10

    - name: Sync Flush
      command: curl -XPOST 'http://{{ es_master_ip }}:9200/_flush/synced'
      register: DRA
      until: DRA|success
      delegate_to: 127.0.0.1
      retries: 5
      delay: 10

  roles:
    - es_cluster_install

  tasks:
    - name: Check if host has rejoined
      command: bash rolling_upgrade_scripts/node_rejoin.sh {{ ansible_hostname }} {{ inventory_hostname }} 
      register: NRJ
      until: NRJ|success
      delegate_to: 127.0.0.1
      delay: 5

    - name: Enable routing allocation
      command: bash rolling_upgrade_scripts/enable_routing_allocation.sh
      register: ERA
      until: ERA|success
      delegate_to: 127.0.0.1
      delay: 10

    - name: Cluster status
      command: bash rolling_upgrade_scripts/cluster_status.sh
      register: CS
      until: CS|success
      delegate_to: 127.0.0.1
      delay: 30
      retries: 5
