---
# Elasticsearch Setup Ansible Playbook
- hosts: es_cluster
  become: yes
  vars_files:
    - es_cluster_install/defaults/main.yml
    - es_cluster_install/vars/main.yml
  tasks:
    - name: elastic-install | Configuring Elasticsearch elasticsearch.yml Node
      template:
        src=es_cluster_install/templates/elasticsearch.yml.j2
        dest={{ elasticsearch_conf_dir }}/elasticsearch.yml
        owner={{ elasticsearch_user }}
        group={{ elasticsearch_group }}
        mode=0644
      when: elasticsearch_conf_dir is defined
      notify: Restart Elasticsearch

    - name : elastic-install | Configure /etc/default/elasticsearch
      template:
        src=es_cluster_install/templates/elasticsearch.default.j2
        dest=/etc/default/elasticsearch
        owner={{ elasticsearch_user }}
        group={{ elasticsearch_group }}
        mode=0644
