---

- name: elasticsearch | Install python-software-properties
  apt:
    pkg=python-software-properties
    state=present
    update_cache=yes
    cache_valid_time={{apt_cache_valid_time}}

- name: elasticsearch | Install dependencies
  apt:
    pkg={{ item }}
    state=present
  with_items: "{{elasticsearch_apt_dependencies}}"

- name: elasticsearch | Ensure temp elasticsearch directories exists
  file:
    path="{{ elasticsearch_work_dir }}"
    state=directory
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    recurse=yes

- name: elasticsearch | Check if we have elastic with same version installed
  stat:
    path="/usr/share/elasticsearch/lib/elasticsearch-{{ elasticsearch_version }}.jar"
  register: installed_version

- name: elasticsearch | Try to stop elasticsearch if running
  service:
    name=elasticsearch
    state=stopped
  ignore_errors: yes
  when: not installed_version.stat.exists

- name: elasticsearch | Download Elasticsearch deb
  get_url:
    url={{ elasticsearch_download_url }}/elasticsearch-{{ elasticsearch_version }}.deb
    dest=/tmp/elasticsearch-{{ elasticsearch_version }}.deb
    mode=0440
  when: not installed_version.stat.exists

- name: elasticsearch | Uninstalling previous version if applicable
  apt:
     name="elasticsearch"
     state="absent"
  when: not installed_version.stat.exists

- name: elasticsearch | Remove elasticsearch directory
  file:
    path="{{ elasticsearch_home_dir }}"
    state=absent
  when: not installed_version.stat.exists

- name: elasticsearch | Install Elasticsearch deb
  shell: dpkg -i -E --force-confnew /tmp/elasticsearch-{{ elasticsearch_version }}.deb
  when: not installed_version.stat.exists
  notify: Restart Elasticsearch

- name: elasticsearch | Ensure elastic directories exists
  file:
    path="{{ item }}"
    state=directory
    follow=yes
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    recurse=yes
  with_items:
     - "{{ elasticsearch_work_dir }}"
     - "{{ elasticsearch_home_dir }}"
     - "{{ elasticsearch_log_dir }}"
     - "{{ elasticsearch_data_dir }}"
     - "{{ elasticsearch_pid_dir }}"
     - "{{ elasticsearch_conf_dir }}"

- name: elasticsearch | Configure elasticsearch.yml
  template:
    src=elasticsearch.yml.j2
    dest={{ elasticsearch_conf_dir }}/elasticsearch.yml
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    mode=0644
  when: elasticsearch_conf_dir is defined
  notify: Restart Elasticsearch

- name: elasticsearch | Configure jvm.options
  template:
    src=jvm.options.j2
    dest={{ elasticsearch_conf_dir }}/jvm.options
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    mode=0644
  when: elasticsearch_conf_dir is defined
  notify: Restart Elasticsearch

- name : elasticsearch | Configure /etc/default/elasticsearch
  template:
    src=elasticsearch.default.j2
    dest=/etc/default/elasticsearch
    owner={{ elasticsearch_user }}
    group={{ elasticsearch_group }}
    mode=0644
  notify: Restart Elasticsearch
