---
- name: rabbitmq_ha_config | checking if rabbitmqadmin is installed
  stat:
    path: /usr/sbin/rabbitmqadmin
  register: rabbitmqadmin_check

- name: rabbitmq_ha_config | install rabbitMQ admin
  shell: wget http://guest:guest@localhost:15672/cli/rabbitmqadmin
  when: not rabbitmqadmin_check.stat.exists

- name: rabbitmq_ha_config | moving the rabbitMQ Admin
  shell: mv rabbitmqadmin /usr/sbin
  when: not rabbitmqadmin_check.stat.exists

- name: rabbitmq_ha_config | making executable rabbitMQ Admin
  shell: chmod +x /usr/sbin/rabbitmqadmin
  notify: restart rabbitmq-server
  when: not rabbitmqadmin_check.stat.exists

- name: rabbitmq_ha_config | creating queue(s)
  command: rabbitmqadmin declare queue name={{ item.queue_name }} durable={{ item.durable|lower }}
  run_once: true
  with_items: "{{ rabbitmq_config }}"
  when: item.queue_name is defined
  #when: ansible_hostname == rabbitmq_master and item.queue_name is defined

- name: rabbitmq_ha_config | setting up ha on queue(s)
  rabbitmq_policy:
    name: "ha-all"
    pattern: "{{ item.policy_pattern }}"
    tags: "{{ item.policy_tags }}"
    state: present
  run_once: true
  with_items: "{{ rabbitmq_config }}"
  when: item.should_set_policy is defined and item.should_set_policy
  #when: ansible_hostname == rabbitmq_master and item.should_set_policy is defined and item.should_set_policy

- name: rabbitmq_ha_config | creating exchange(s)
  command: rabbitmqadmin declare exchange name={{ item.exchange_name }} type={{ item.type }} durable={{ item.durable|lower }}
  run_once: true
  with_items: "{{ rabbitmq_config }}"
  when: item.exchange_name is defined
  #when: ansible_hostname == rabbitmq_master and item.exchange_name is defined

- name: rabbitmq_ha_config | creating binding(s)
  command: rabbitmqadmin declare binding source={{ item.exchange_name }} destination_type="queue" destination={{ item.queue_name }} routing_key={{ item.routing_key }}
  run_once: true
  with_items: "{{ rabbitmq_config }}"
  when: item.exchange_name is defined and item.queue_name is defined
  #when: ansible_hostname == rabbitmq_master and item.exchange_name is defined and item.queue_name is defined